Basic_Login/Basic_Login/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import include
from LoginApp import views

urlpatterns = [
    re_path(r'^$',views.index,name = 'index'),
    re_path(r'^LoginApp/',include('LoginApp.urls')),
    re_path(r'^logout/$',views.user_logout,name = 'logout'),
    re_path(r'^special/',views.special,name = 'special'),

    path('admin/', admin.site.urls),
]

Basic_Login/LoginApp/urls.py
from django.urls import re_path
from LoginApp import views

app_name = 'LoginApp'

urlpatterns = [

    #re_path(r'^register',views.registration,name = 'registration'),
    re_path(r'^register/',views.register,name = 'register'),
    re_path(r'^user_login/$',views.user_login,name = 'user_login'),
]

Basic_Login/LoginApp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfileInfo(models.Model):

    #this user will fetch field from User class
    user = models.OneToOneField(User,on_delete = models.CASCADE)

    #additional field

    portfolio_site = models.URLField(blank = True)

    profile_pic = models.ImageField(upload_to = 'profile_pic', blank = True )

    def __str__(self):
        return self.user.username

Basic_Login/LoginApp/forms.py
from django import forms
from django.contrib.auth.models import User
from LoginApp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

Basic_Login/LoginApp/views.py
from django.shortcuts import render
from LoginApp.forms import UserForm,UserProfileInfoForm

#this library for user_login so use it when you want to login
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout


# Create your views here.11
def index(call):
    return render(call,'home_page/index.html')

def registration(call):
    return render(call,'home_page/registration.html')

"""def login(call):
    return render(call,'home_page/login.html')
"""
@login_required
def special(call):
    return HttpResponse('Hey u logged in')

@login_required
def user_logout(call):
    logout(call)
    return HttpResponseRedirect(reverse('index'))



def register(call):

    registered = False #beacuse in registration.hyml we make condition if registered than thanks else form so we have to give False here

    if call.method == 'POST':

        user_form = UserForm(data = call.POST) #this line will refer to the forms.py

        profile_form = UserProfileInfoForm(data = call.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save() # this line will refer to model.py
            user.set_password(user.password)
            user.save()
            #end of user_form set_password beacuse we have add password in forms.py in additional fields

            profile = profile_form.save(commit = False) #false because it will overlapped upper form so for that we use onetoone fields to use that next line

            profile.user = user

            if 'profile_pic' in call.FILES:
                profile.profile_pic = call.FILES['profile_pic']

            profile.save()
            registered = True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(call,'home_page/registration.html',{
                            'user_form':user_form,
                            'profile_form':profile_form,
                            'registered':registered,
                        })


def user_login(call):

    if call.method == 'POST':
        username = call.POST.get('username') # get name from html file from login.html
        password = call.POST.get('password')

        user = authenticate(username = username,password = password) # this authenticate with databases

        if user:
            if user.is_active:
                login(call,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('Account is not active')

        else:
            print('someone tried to login but failed')
            print('UserName:{} and password:{}'.format(username,password))
            return HttpResponse('Invalid Credits')

    else:
        return render(call,'home_page/login.html',{})

Basic_Login/templates/home_page/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Local Site</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>

    <nav class = "navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class = "nav navbar-nav">
          <li> <a class="navbar-brand" href="{% url 'index' %}">Index</a> </li>
          <li> <a class="navbar-link" href="{% url 'LoginApp:register' %}">Registration</a> </li>
          <li> <a class="navbar-link" href="{% url 'admin:index' %}">Django Admin</a> </li>

          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'LoginApp:user_login' %}">Login</a> </li>
          {% endif %}
        </ul>

      </div>
    </nav>
    <hr class="my-4 solid" >
    <div class="container">

      {% block body_block %}
      <!-- Anything in this part gonna print so upper is header and below part is yout footer-->
      {% endblock %}

    </div>
  </hr>

  </body>
  </html>

  <!-- this file is for reuse parts for every pages to indluded in base file like header.php and footer.php

Basic_Login/templates/home_page/index.html
<!DOCTYPE html>
{% extends 'home_page/base.html' %}

{% block body_block %}

<h1>Wel come To In The Dex Page </h1>

{% endblock %}

Basic_Login/templates/home_page/login.html
<!DOCTYPE html>
{% extends 'home_page/base.html' %}

{% block body_block %}

<div class="jumbotron" >
  <h1>Please Login</h1>
  <form  method="post">
    {% csrf_token %}
    <label for="username">UserName:</label>
    <input type="text" name="username" placeholder="Enter UserName">

    <label for="password">Password:</label>
    <input type="text" name="password" placeholder="Enter Password">

    <input type="submit" name="" value="login">
  </form>

</div>

{% endblock %}

Basic_Login/templates/home_page/registration.html
<!DOCTYPE html>
{% extends 'home_page/base.html' %}

{% block body_block %}

<div class="jumbotron">
  {% if registered %} <!--this is funcion in views.py -->
        <h1>Hey You registered </h1>
  {% else %}
    <h1>Register booth</h1>
    <h1>Fill Out the Form </h1>

    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type = "submit" value="Register" >
    </form>
  {% endif %}
</div>

{% endblock %}